#!/bin/sh
#================================================================
# bov-tb
#================================================================
#% SYNOPSIS
#+    bov-tb reads results <image>
#%
#% DESCRIPTION
#%    Run the pipeline in a new docker container
#%
#% INPUTS
#%    reads        Absolute filepath to directory of .fastq.gz reads
#%    results      Absolute filepath to where nextflow results will be written
#%    <image>      (optional) docker image to use. Default: aaronsfishman/bov-tb:latest

READS=$1
RESULTS=$2
IMAGE=${3:-aaronsfishman/bov-tb:latest}

sudo docker run --rm -it -v $READS:/reads/ -v $RESULTS:/results/ $IMAGE
