#!/bin/sh
#================================================================
# btb-seq
#================================================================
#% SYNOPSIS
#+    bov-tb reads_dir results_dir
#%
#% DESCRIPTION
#%    Run the pipeline on a batch of samples.
#%
#% INPUTS
#%    reads        filepath to directory of .fastq.gz read pairs
#%    results      filepath to where nextflow results will be stored
#%    profile      profile under which to run btb-seq (local/awsbatch)

READS=$1
RESULTS=$2
PROFILE=${3:-local} 

nextflow run ./bTB-WGS_process.nf --outdir $RESULTS --reads $READS/"*_{S*_R1,S*_R2}*.fastq.gz" -with-report "$RESULTS/report.html" -profile $PROFILE -bucket-dir s3://nxflow-work/work/ -resume
