#!/bin/bash
#
#================================================================
# run_tests
#================================================================
#
#% DESCRIPTION
#%    Runs integration tests
#%    Each test should be defined as a bash script and appended in the JOBS variable below

JOBS=(
    minimal-pipeline.bash
)

IMAGE=bov-tb-test
BASEDIR=$PWD/$(dirname "$0")

# Build docker image
echo ==========================
echo Build
echo ==========================

sudo docker build -t $IMAGE $BASEDIR/../
if [ $? -ne 0 ]; then
    echo *** BUILD FAILED JOB ***
    exit 1
fi

# Integration Tests
for i in "${JOBS[@]}"
do
    echo ==========================
    echo $i
    echo ==========================

    # Run job in docker
    sudo docker run -v $BASEDIR/jobs:/jobs/ --rm $IMAGE /bin/bash -e /jobs/$i
    exitcode=$?

    # Handle exit code
    if [ $exitcode -ne 0 ]; then
        echo
        echo *** JOB FAILED: $i ***
        echo
        exit 1
    else
        echo
        echo --- JOB PASSED: $i ---
        echo
    fi
done

echo ==========================
echo ALL TEST PASSED
echo ==========================
