name: CI tests using nf-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Nextflow latest
        uses: nf-core/setup-nextflow@v1
        with:
          version: '25.04.2'

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run Tests
        run: nf-test test --ci

      - name: Archive test outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bam file
          path: /home/runner/work/**/.nf-test/**/*.bam
