#!/bin/sh
#
#================================================================
# print_todays_wgs_cluster.sh
#================================================================
#
#% DESCRIPTION
#%    Prints the filepath of the WGS Cluster CSV if it were generated by nextflow today. 

TODAY=`date +%d%b%y`
echo /results/Results_reads_${TODAY}/reads_AssignedWGSCluster_${TODAY}.csv