#!/bin/sh
#
#================================================================
# print_todays_wgs_cluster.sh
#================================================================
#
#% DESCRIPTION
#%    Prints the file location of the WGS Cluster CSV if it were generated by nextflow today. 


TODAY=`date +%d%b%y`
echo Results_reads_$TODAY/reads_AssignedWGSCluster_${TODAY}.csv