#!/bin/sh
#
#================================================================
# print_todays_wgs_cluster.sh
#================================================================
#
#% DESCRIPTION
#%    Prints the file location of the WGS Cluster CSV if it were generated by nextflow today. 

name=$1

TODAY=`date +%d%b%y`
echo Results_${name}_${TODAY}/${name}_AssignedWGSCluster_${TODAY}.csv